### ISSUE TITLE
keycloak-issue

### ISSUE THREAD

**Issue by lakshithajayasinghe** [ChimbuChinnadurai/spring-cloud-dataflow-keycloak-integration#1]
Hi @ChimbuChinnadurai ,
as you, re guidance, I added yml file, but some attributes are getting highlighted.I added some maven dependencies also but nothing happened .please check the following image. and another thing is I want to know if I am using dataflow server only no need to modify the skipper server I am I write? i mean without a skipper server I can able to run a dataflow server with keycloak write?
i am using IntelliJ idea to edit yml and dataflow server 

![error-SCDF-2](https://user-images.githubusercontent.com/73877677/104209805-2b956b80-5458-11eb-869d-7276f3fd1c39.PNG)

**Comment by ChimbuChinnadurai** [comment]
Hi @pptllakshitha - no maven dependency is required for this configuration and this config file is specific to Kubernetes if you want to install it via helm charts. And yes, you can have this security configuration only in dataflow server to get it to work but it is not recommended since skipper will not have any security enabled.
